use customerdb;
select*from project2;

# what is the total revenue generated by male vs female?
select gender, sum(purchase_amount) as revenue
from project2
group by gender;

#which customer used a discount but still spent more than the average purchase amount?
select customer_id ,purchase_amount
from project2
where discount_applied='yes' and purchase_amount >= (select avg(purchase_amount) from project2);

#which are the top 5 products with the highest average review rating ?
SELECT 
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS average_product_rating
FROM project2
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;

#compare the average purchase amounts between standard and express shipping
select shipping_type,
round(avg(purchase_amount),2)
from project2
where shipping_type in ('Standard','Express')
group by shipping_type;

#do subscribed customers spend more ?compare average spend and total revenue between subscribe and non-subscribed customer 
select subscription_status ,
count(customer_id) as Total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from project2
group by subscription_status
order by avg_spend,total_revenue desc;

#which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) 
        / COUNT(*) * 100.0, 
    2) AS discount_rate
FROM project2
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#segment customers into new,returming and loyal based on their total number
#..of previous purchases and show the count of each segment 

with customer_type as (
select customer_id,previous_purchases,
case
when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from project2
)
select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment;

#what are the top 3 most purchased products within each category ?
with item_counts as (
select category,
item_purchased ,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from project2
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts 
where item_rank<=3;

# are customers who are repeat buyers(more than 5 purchases) also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from project2
where previous_purchases > 5
group by subscription_status ;

#what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from  project2
group by age_group
order by total_revenue desc;


